mysql:
  host: localhost
  port: 3306
  username: root
  password: root

spring:
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    host: 47.104.141.27
    port: 5672

server:
  port: 8080