spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  rabbitmq:
    username: Lanny
    password: Lanny
#    virtual-host: /
    host: 192.168.1.121
    port: 5672

server:
  port: 8081