mysql:
  host: localhost
  port: 3306
  username: root
  password: renxuehui

spring:
  rabbitmq:
    username: Lanny
    password: Lanny
    virtual-host: /
    host: 127.0.0.1
    port: 5672
  datasource:
    username: root
    password: renxuehui
    url: jdbc:mysql://localhost:3306/se?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081