mysql:
  host: localhost
  port: 3306
  username: root
  password: 123456

spring:
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/se?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081